Small nerfs
Jolly-66/JollyStationCode pull request #104
Opened 2021-10-30 01:48 UTC by Jolly-66

Just small nerfs, nothing to see here.

1. Smuggler satchels can no longer be put into other bags
2. Legions will no longer spawn as antag roles, instead as clowns. They also now spawn more as lizards, having their lizard and human chance swapped.

2021-10-30 01:51 UTC, CRITAWAKETS commented
aw dammit i loved the really rare random nukie suit

though of course you can just raid the place in lavaland that has a nukie suit that almost nobody notices.

+1 on the smuggler's satchels btw

2021-10-30 01:53 UTC, CRITAWAKETS commented
Actually, did you change the shadowlegion? It's supposed to spawn with a shadow mutation toxin pill if i renember correctly.

2021-10-30 01:54 UTC, Jolly-66 commented
> Actually, did you change the shadowlegion? It's supposed to spawn with a shadow mutation toxin pill if i renember correctly.

I removed it, I just find it weird, getting a random mutation toxin for a species.. we already kinda have enabled from the start.

2021-10-30 01:55 UTC, CRITAWAKETS commented
Yeah i kinda feel enabled-species does make it useless. I guess i could work on changing xenobio to be able to make mutation toxins for more species as that would be more sensical.

Also for the 1% chance you should still give shadow a cool thing. Doesnt have to be strong, just has to be cool.

2021-11-01 08:40 UTC, MrMelbert requested changes

2021-11-01 08:40 UTC, MrMelbert commented on jollystation_modules/code/modules/mob/living/simple_animal/hostile/mining_mobs/hivelord.dm
> +/obj/effect/mob_spawn/human/corpse/damaged/legioninfested/Initialize(mapload)
i _doubt_ this works and would like to see it tested
(bump up the weights to 100 and spawn/kill a lot)

2021-11-01 08:41 UTC, MrMelbert commented
also `>They also now spawn more as lizards, having their lizard and human chance swapped.` explain this

2021-11-01 11:02 UTC, Jolly-66 commented
> also `>They also now spawn more as lizards, having their lizard and human chance swapped.` explain this

I just copied the code; humans had like a 67 chance to spawn, lizards were 2X something, so I just swapped these values because, yknow, lizard station

2021-11-01 16:41 UTC, Jolly-66 commented on jollystation_modules/code/modules/mob/living/simple_animal/hostile/mining_mobs/hivelord.dm
> +/obj/effect/mob_spawn/human/corpse/damaged/legioninfested/Initialize(mapload)
I did test this, and from what I concluded most were lizards. I'll get a vid in a bit if you want further proof.

2021-11-07 05:56 UTC, CRITAWAKETS commented on jollystation_modules/code/modules/clothing/spacesuits/hardsuit.dm
> +	desc = "A dual-mode advanced hardsuit designed for work in special operations. It is in EVA mode. Property of Gorlex Marauders."
needs some kind of indicator in the description, something like "Property of Donk Co."

2021-11-07 05:56 UTC, CRITAWAKETS commented on jollystation_modules/code/modules/clothing/spacesuits/hardsuit.dm
> +	helmettype = /obj/item/clothing/head/helmet/space/hardsuit/syndi
Why is this the real helmet?

2021-11-07 12:21 UTC, Jolly-66 commented on jollystation_modules/code/modules/clothing/spacesuits/hardsuit.dm
> +	helmettype = /obj/item/clothing/head/helmet/space/hardsuit/syndi
do not code at 1am

2021-11-07 19:56 UTC, CRITAWAKETS commented on jollystation_modules/code/modules/clothing/spacesuits/hardsuit.dm
> +	name = "a silly blood-red hardsuit"
something something "the action does nothing to the a silly blood-red hardsuit!"

2021-11-07 21:23 UTC, Jolly-66 commented on jollystation_modules/code/modules/clothing/spacesuits/hardsuit.dm
> +	name = "a silly blood-red hardsuit"
You are speaking coder to me and I do not comprehend

2021-11-07 22:40 UTC, CRITAWAKETS commented on jollystation_modules/code/modules/clothing/spacesuits/hardsuit.dm
> +	name = "a silly blood-red hardsuit"
remove the "a" otherwise text will look weird

2021-11-10 05:18 UTC, MrMelbert requested changes

2021-11-10 05:18 UTC, MrMelbert commented on jollystation_modules/code/modules/mob/living/simple_animal/hostile/mining_mobs/hivelord.dm
> +/obj/effect/mob_spawn/human/corpse/damaged/legioninfested/Initialize(mapload)
i don't see why this file needs to exist still

2021-11-15 09:52 UTC, merged