Adds Item Dispensers
Jolly-66/JollyStationCode pull request #114
Opened 2021-11-10 04:22 UTC by Wallemations

I remembered how horrible my first attempt at adding to this codebase went so I wanted to try redeeming myself by porting something I made myself, entirely modular.
## Okay but what is it
Item Dispensers, they're like stationary boxes built specifically for walls. Only accepts a single type of item _(and any of its children, but that's fun so I kept it)_.
They're great for reducing that nasty box clutter from your precious tables, racks, and shelves.
### Here is an example of what you can expect with item dispensers:

https://user-images.githubusercontent.com/66052067/141048985-24ee6b4e-dbba-4837-9b23-d133d5f8e614.mp4

The pre-made ones come in 7 flavors...
![12](https://user-images.githubusercontent.com/66052067/141049050-4382a57d-45d9-41a0-9d94-cc4c92ae1b4a.PNG)

And there's even a wallmount for an empty one for you to fill up yourself!

https://user-images.githubusercontent.com/66052067/141049124-e9410b29-70d2-4ca7-833c-43b7264f464b.mp4

Clearly a server without item dispensers is a server that's missing out.
So get item dispensers today!

2021-11-10 04:38 UTC, CRITAWAKETS commented
https://youtu.be/IJDgkrtUlTc

2021-11-10 05:26 UTC, MrMelbert reviewed
Looks pretty cool

2021-11-10 05:26 UTC, MrMelbert commented on jollystation_modules/code/game/objects/structures/item_dispensers.dm
> +			balloon_alert(user, "You insert [I] into [src].")
Balloon alerts are typically un-capitalized, concise, and un-punctuated and 
```suggestion
			balloon_alert(user, "inserted [I]")
```

2021-11-10 05:26 UTC, MrMelbert commented on jollystation_modules/code/game/objects/structures/item_dispensers.dm
> +			to_chat(user, span_notice("You can't fit more [item_name]\s in [src]!"))
```suggestion
			to_chat(user, span_warning("You can't fit [item_name] into [src]!"))
```

2021-11-10 05:26 UTC, MrMelbert commented on jollystation_modules/code/game/objects/structures/item_dispensers.dm
> +		balloon_alert(user, "You take \a [item_name] from [src]")
```suggestion
		balloon_alert(user, "removed [item_name]")
```

2021-11-10 05:53 UTC, Wallemations commented on jollystation_modules/code/game/objects/structures/item_dispensers.dm
> +			balloon_alert(user, "You insert [I] into [src].")
Ah, good to know, I'll be sure to fix that in the morning

2021-11-10 10:47 UTC, Jolly-66 reviewed
If the sprites are from goon put them in the goon folder please

2021-11-10 10:50 UTC, Jolly-66 commented
When I get home today I'm dropping a few more comments

Fuck mobile reviews

2021-11-10 18:11 UTC, Wallemations commented
> If the sprites are from goon put them in the goon folder please 

Do I put the custom ones in the goon folder too or just the ones directly from goon

2021-11-10 19:12 UTC, Jolly-66 commented
> Do I put the custom ones in the goon folder too or just the ones directly from goon

If you made sprites keep them separate but since Goon has a different copyright than TG, I don't wanna get in trouble with them, even tho their chances of looking here are slim to none, I want to respect what TG does.

Also, per the rules, if you can, please make sure to credit the OG spriters.

2021-11-10 19:15 UTC, Jolly-66 requested changes
I personally hate brick comments, just simplify them down and we'll be fine.

Clean code is happy code!

2021-11-10 19:15 UTC, Jolly-66 commented on jollystation_modules/code/game/objects/structures/item_dispensers.dm
> +//////  Pre-set Dispensers  //////
```suggestion
//Pre-set Dispensers
```

2021-11-10 19:15 UTC, Jolly-66 commented on jollystation_modules/code/game/objects/structures/item_dispensers.dm
> +//////      Dispensers      //////
```suggestion
//Dispensers, sprites from Goon.
```

2021-11-10 19:15 UTC, Jolly-66 commented on jollystation_modules/code/game/objects/structures/item_dispensers.dm
> +/// Wallframe for custom dispensers ///
```suggestion
//Preset Dispensers, Wallframe version
```

2021-11-10 22:16 UTC, Wallemations commented
Git didn't remove the merge conflict tag automatically even though it's fixed
This is so sad

2021-11-10 22:51 UTC, Jolly-66 commented
> Git didn't remove the merge conflict tag automatically even though it's fixed This is so sad

Don't worry about it

2021-11-10 23:18 UTC, Jolly-66 approved these changes
:+1:

Unless @MrMelbert has any final comments

2021-11-12 18:23 UTC, Wallemations commented
Hold on just found out `plural_s()` is a proc

2021-11-22 21:49 UTC, merged