[DNM] JollyStation Job Expansion Part 1
Jolly-66/JollyStationCode pull request #73
Opened 2021-08-11 14:40 UTC by Jolly-66

Well, fuck. Here we go.

This PR adds the **Asset Protection**, JollyStations equal to Skyrats BlueShield.

# Bridge Officer changes
The BOs new job is this, assisting the Heads of Staff or Chain of Command, if you will, with filing the influx of station paperwork. Lawyers and HoPs can assist too! (This change is ONLY on Pubby as of now. Lima will be updated in the future)

The BO will listen to the Chain of Command **and** Head of Personnel (this is flavor text and can be regularly disregarded).

The BO is no longer considered a pseudo sec-command member, but is now like the captain, who is just a command rep.

The BO lost most of its security assets, including some armor. BOs have an armor vest in their locker that is much weaker than the APs, but should still provide some durability in the event someone breaches the bridge.

BO now has RC and card auth access. Removed a chunk of security access as well as `ACCESS_head`; this change was made only since this define is used in opening their lockers. If somewhere later we can redefine this we will, but for now this change will stay.

The BO has taken on a much more formal attire, fitted with white gloves and lace up shoes. Don't make them dirty up their uniform now!

<details>
<summary>Sprites/Images</summary>

AP (left) and BO (right) locker resprites
![image](https://user-images.githubusercontent.com/70232195/129048816-88908bdf-fed9-41db-86fe-bdf79c03768c.png)

AP secHUD, BO secHUD
![image](https://user-images.githubusercontent.com/70232195/129048689-04abb2d3-7342-4ca7-ac98-2dbe97c4dd11.png)

PubbyStation AP/BO office
![image](https://user-images.githubusercontent.com/70232195/129048704-4ff22d8a-5a35-4546-8fa0-60b26a9013ed.png)

</details>

# Asset Protection addition
The protector of assets, the guard of asses, meet the Asset Protection. Their job is to guard a Chain of Command member at their leisure, following them around. This can be represented by one of their 5 departmental armbands. May add one later for security.

The AP has taken most of the pseudo security BO had, including its armored beret and vests. The AP has a stronger armor vest in their locker, but due to the bulky nature of it, will slow them down.

The AP will listen to the Chain of Command **and** Head of Security (this is flavor text and can be regularly disregarded).

The AP has an.. oddly familiar outfit with that black tie. Must be a coincidence. 

# Misc changes

QM finally has proper head represnetation in the form of their ID and secHUD icon. Viva la revolution.

Sprites for the BO locker have been updated. Added AP locker sprites.

Landmark sprites for BO, Toxicologist and Xenobiologist have been updated. Added the AP sprite.

Turf icon from the BO office has been updated. Added the AP office turf icon.

Icon for service armband has been added.

Modular change made to direct the overlay of _under.dm to our file. Any changes upstream to the master .dmi should be added to ours.

<details>
<summary>Misc stuff</summary>

Viva la revolution.
![image](https://user-images.githubusercontent.com/70232195/129049046-c9b4ef05-eef6-4d6d-ae04-36211a50405b.png)

AP/BO office turf icons
![image](https://user-images.githubusercontent.com/70232195/129049137-9eeef703-b440-4153-adce-c1babdee7feb.png)

Update custom job spawners. Excuse the crunched moth.
![image](https://user-images.githubusercontent.com/70232195/129049235-5db09e6e-87f5-4434-90e8-636b5f09d4be.png)

A horrible service armband
![image](https://user-images.githubusercontent.com/70232195/129049327-959355c7-4c9e-433f-bf91-eb2cebcd6456.png)

</details>

2021-08-11 19:16 UTC, MrMelbert commented on code/modules/clothing/under/_under.dm
> +	accessory_overlay = mutable_appearance('jollystation_modules/icons/mob/clothing/accessories.dmi', "[accessory_color]") //NON-MODULE CHANGE, is there a different way we can do this?
there is a better way of going about this, instead of needing to copy the entire file

instead define a variable on `/obj/item/clothing/accessory`, something like `var/overlay_file = `'icons/mob/clothing/accessories.dmi'`

then on your custom made accessory set `overlay_file  = 'jollystation_modules/icons/mob/clothing/accessories.dmi'`

then instead of hardcoding the file above, just refer to the variable

2021-08-11 19:16 UTC, MrMelbert commented on code/modules/jobs/jobs.dm
> +	"Asset Protection", // NON-MODULE CHANGE
hindsight being 20/20, you probably should've waited for the 2nd job refactor PR to go through before working on this job related PR

this list won't exist in the ftuure

2021-08-11 19:16 UTC, MrMelbert commented on jollystation_modules/code/game/objects/effects/landmarks.dm
> +/obj/effect/landmark/start/asset_protectionasset_protection
interesting typepath

2021-08-11 19:16 UTC, MrMelbert commented on jollystation_modules/code/game/objects/effects/landmarks.dm
> +//Just copy pasted from the BO shit, Melbert don't kill me
haha you know i'm gonna comment on it

I think this should rather be a "locker" landmark with the base behavior, with subtypes to spawn certain types instead of copy+pasted twice

2021-08-11 19:16 UTC, MrMelbert commented on jollystation_modules/code/game/objects/items/devices/radio/headset.dm
> +	name = "\proper the asset protection's headset"
seeing the name in a proper setting, I feel like it should be something like "asset protection officer" when used in this form, "asset protection" otherwise

2021-08-11 19:16 UTC, MrMelbert commented on jollystation_modules/code/game/objects/structures/crate_lockers/closets/secure/asset_protection.dm
> +	name = "Asset Protection Equipment Beacon"
this should also be generalized into a locker spawner instead of copy+pasted

2021-08-11 19:16 UTC, MrMelbert commented on jollystation_modules/code/modules/clothing/suits/armor.dm
> +	slowdown = 1
slowdown 1 on a normal suit of armor will never get used, that's as slow as a hardsduit without the space protection / increased armor that a hardsuit has

just keep it as an alt cosmetic

2021-08-11 19:16 UTC, MrMelbert commented on jollystation_modules/code/modules/clothing/under/jobs/security.dm
> +	armor = list(MELEE = 15, BULLET = 0, LASER = 0, ENERGY = 0, BOMB = 0, BIO = 0, RAD = 0, FIRE = 50, ACID = 50, WOUND = 5)
i don't recommend going above 10 melee armor for jumpsuits

2021-08-11 19:16 UTC, MrMelbert commented on jollystation_modules/code/modules/jobs/job_types/asset_protection.dm
> +			r_pocket = /obj/item/assembly/flash
i don't like that the meme rare flash is shared between both of the two jobs, makes it less special imo

2021-08-14 07:44 UTC, MrMelbert requested changes

2021-08-14 07:44 UTC, MrMelbert commented on jollystation_modules/code/game/objects/effects/landmarks.dm
> +GLOBAL_LIST_EMPTY(asset_protection_lockers)
don't need these

2021-08-14 07:44 UTC, MrMelbert commented on jollystation_modules/code/game/objects/effects/landmarks.dm
> +GLOBAL_LIST_EMPTY(locker_landmark)
also very minor thing but
```suggestion
// Global list for generic lockers
GLOBAL_LIST_EMPTY(locker_landmarks)
```

2021-08-14 07:44 UTC, MrMelbert commented on jollystation_modules/code/game/objects/effects/landmarks.dm
> +/obj/effect/landmark/locker_spawner/spawn_anchored
this subtype can be killed

2021-08-14 07:44 UTC, MrMelbert commented on jollystation_modules/code/game/objects/effects/landmarks.dm
> +
... and instead, make `spawn_anchored` subtypes for both of these

2021-08-14 07:44 UTC, MrMelbert commented on jollystation_modules/code/game/objects/structures/crate_lockers/closets/secure/asset_protection.dm
> +/obj/item/asset_protection_locker_spawner
I still would like this changed into an `/obj/item/locker_spawner` with asset protection and bridge officer subtypes instead of copy+pasted

2021-08-14 07:44 UTC, MrMelbert commented on jollystation_modules/code/modules/clothing/suits/armor.dm
> +	armor = list(MELEE = 40, BULLET = 40, LASER = 40, ENERGY = 40, BOMB = 30, BIO = 0, RAD = 0, FIRE = 100, ACID = 90, WOUND = 10)
the armor values are inherited from its parent, you don't need to copy+paste it

2021-08-14 07:44 UTC, MrMelbert commented on jollystation_modules/code/modules/clothing/under/accessories.dm
> +	var/overlay_icon = "null"
`overlay_icon` is unused, no need to keep it

2021-08-15 01:38 UTC, Jolly-66 commented
Worst comes to worst I finish this up when I get home sometime next week

Shouldn't be tooooooo much

2021-08-22 22:36 UTC, MrMelbert requested changes
Add Asset Protection to `get_modular_PDA_regions()`.

2021-08-22 22:36 UTC, MrMelbert commented on jollystation_modules/code/modules/jobs/access.dm
> +	return list("Xenobiologist", "Toxicologist", "Bridge Officer", "Asset Protection")
Make sure to check that `get_all_module_heads()` below has the jobs you want and don't want.

2021-08-22 22:36 UTC, MrMelbert commented on jollystation_modules/code/modules/jobs/job_types/asset_protection.dm
> +	req_admin_notify = 1
```suggestion
	req_admin_notify = TRUE
```

2021-08-22 22:36 UTC, MrMelbert commented on jollystation_modules/code/modules/jobs/job_types/asset_protection.dm
> +	job_flags = JOB_ANNOUNCE_ARRIVAL | JOB_CREW_MANIFEST | JOB_EQUIP_RANK | JOB_CREW_MEMBER | JOB_NEW_PLAYER_JOINABLE
```suggestion
	job_flags = JOB_ANNOUNCE_ARRIVAL | JOB_CREW_MANIFEST | JOB_EQUIP_RANK | JOB_CREW_MEMBER | JOB_NEW_PLAYER_JOINABLE | JOB_BOLD_SELECT_TEXT | JOB_REOPEN_ON_ROUNDSTART_LOSS
```

2021-08-22 22:36 UTC, MrMelbert commented on jollystation_modules/code/modules/jobs/job_types/asset_protection.dm
> +	glasses = /obj/item/clothing/glasses/hud/security/sunglasses
```suggestion
```
no jobs spawn with hudglasses. Make it normal sunglasses

2021-08-22 22:36 UTC, MrMelbert commented on jollystation_modules/code/game/objects/effects/landmarks.dm
> +	spawn_anchored = TRUE
```suggestion
```

if you need it to spawn anchored, make a subtype that spawns anchored, don't make the base type spawn anchored

2021-08-22 22:36 UTC, MrMelbert commented on jollystation_modules/code/game/objects/items/locker_spawners.dm
> +//For jobs primarily on Runtime/main stations
```suggestion
// Given to jobs that join stations not compatible with their job (IE, modular jobs on non-modular stations).
```

2021-08-22 22:36 UTC, MrMelbert commented on jollystation_modules/code/game/objects/structures/crate_lockers/closets/secure/asset_protection.dm
> +	. = ..()
```suggestion
```
This parent call is actually not necessary afaik

2021-08-22 22:36 UTC, MrMelbert commented on jollystation_modules/code/game/objects/structures/crate_lockers/closets/secure/bridge_officer.dm
>  	. = ..()
```suggestion
```
Same with this one from where you copied it

2021-08-23 05:52 UTC, MrMelbert commented on jollystation_modules/code/game/objects/effects/landmarks.dm
>  	spawn_anchored = TRUE
```suggestion
```
a

2021-08-23 05:52 UTC, MrMelbert commented on jollystation_modules/code/modules/clothing/under/accessories.dm
> +	overlay_icon = "servband"
```suggestion
```

2021-08-23 05:52 UTC, MrMelbert commented on jollystation_modules/code/modules/jobs/job_types/asset_protection.dm
> +	// If the map we're on doesn't have a brige officer locker, add in a way to get one
```suggestion
	// If the map we're on doesn't have a ap locker, add in a way to get one
```

2021-08-23 06:07 UTC, merged